# action.yml
name: 'Create latexdiff'
description: 'Create a file highlighting differences between two latex documents'
inputs:
  main-file:  # name of main latex file
    description: 'Name of main latex file'
    required: true
    default: 'main.tex'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.main-file }}
