on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate a diff file
        uses: egor-demidov/create-latexdiff@main
        with:
          main-file: 'main.tex'
      - name: Upload diff file artifact
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}
